### ISSUE TITLE
hard triplet convergence

### ISSUE THREAD

**Issue by ffredd** [NegatioN/OnlineMiningTripletLoss#16]
I use triple loss between data of two modalities to reduce the distance between different modalities of the same class and increase the distance between different modalities  of different class. But when I use batch_all loss, the valid set loss has not changed; now using hard_loss, the valid set loss still has not changed. What is the reason? I found some answers that triplet is difficult to converge. What do you do to deal with triplet loss convergence?

**Comment by ffredd** [comment]
why u closed this issue



---Original---
From: "Joakim ***@***.***&gt;
Date: Sat, Sep 24, 2022 16:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NegatioN/OnlineMiningTripletLoss] hard triplet convergence(Issue #16)




 
Closed #16 as completed.

**Comment by NegatioN** [comment]
Because I don't really have a good answer for you, and it's not strictly related to the library.
