### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by rohit-gupta** [NegatioN/OnlineMiningTripletLoss#2]
Hi Joakim,

This is a great implementation of batch-hard and batch-all triplet sampling, and I would like to use it for my work and even contribute to it. In this regard, is it possible for you to add a license to this project ? 

Rohit

**Comment by NegatioN** [comment]
Hey @rohit-gupta ! I added an MIT license now, feel free to ping me if that doesn't allow for what you need.

**Comment by rohit-gupta** [comment]
@NegatioN That is perfect, thank you very much !
