### ISSUE TITLE
RuntimeError: Expected object of scalar type Bool but got scalar type Byte for argument #2 'other' in call to _th_and

### ISSUE THREAD

**Issue by x-dragonet** [NegatioN/OnlineMiningTripletLoss#4]
When I use your code, I meet the following error.  File "triplet_loss.py", line 171, in _get_anchor_positive_triplet_mask
![image](https://user-images.githubusercontent.com/20591783/71615492-9cbb0580-2bec-11ea-9d82-01694207bbdc.png)

My Pytorch version is 1.30 & Python version is 3.7.4

**Comment by NegatioN** [comment]
This code is written for pytorch version: torch-1.0.1.post2

So at some point, maybe 1.1, they changed some return values from Byte to Bool. If you wanna make a patch for that, that would be great :)

**Comment by NegatioN** [comment]
This is now fixed if you install it from pip according to the readme @x-dragonet
