### ISSUE TITLE
CUDA ERROR on using GPU tensors with batch_all_triplet_loss function

### ISSUE THREAD

**Issue by sidgairo18** [NegatioN/OnlineMiningTripletLoss#6]
Why is `device` argument not provided for the `batch_all_triplet_loss()` function as is done for `batch_hard_triplet_loss(labels, embeddings, margin, squared=False, device='cpu')`?

On giving cuda tensor to the `batch_all_triplet_loss()` function a CUDA ERROR is thrown.

**Comment by NegatioN** [comment]
Oh I'm sorry about that, that's just a mistake on my end :slightly_smiling_face: Thanks for pointing it out.
I might fix it eventually, but I'd obviously accept a PR for it as well. Even better is probably just to use the device-type of the incoming tensor to do everything, instead if manually passing it.
